name: CI
on:
  push:
jobs:

  build:
   
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      - name: git version
        run : git --version
      - name: mvn version
        run : mvn --version
      - name: tomcat deploy
        run : curl -v -u admin:admin -T /home/runner/work/target/spring3-mvc-maven-xml-hello-world-1.2.war 'http://ec2-18-191-187-222.us-east-2.compute.amazonaws.com:8080/manager/text/deploy?path=/github_action_spring3'

